<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{95fa86a7-2031-4ef9-9bc3-09dd08f854df}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test : STRING := 'hello'; //this is a test variable to place in the textbox on the HMI
	//SAFE
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>